# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EY5LQK-AYW1QkvOYdlKTn6uxzE5G1uCD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

import os
import glob
import kagglehub
import pandas as pd


path = kagglehub.dataset_download("blastchar/telco-customer-churn")
print("Path to dataset files:", path)


csv_path = glob.glob(os.path.join(path, "*.csv"))[0]
df = pd.read_csv(csv_path)


print("--- İlk 5 Satır ---")
print(df.head())

print("\n--- Veri Tipleri ve Bilgisi ---")
print(df.info())

df.drop('customerID', axis=1, inplace=True)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})
df = pd.get_dummies(df, drop_first=True)

X = df.drop('Churn', axis=1)
y = df['Churn']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

log_model = LogisticRegression(max_iter=1000, random_state=42)
log_model.fit(X_train_scaled, y_train)

y_pred = log_model.predict(X_test_scaled)

print("\n--- Model Başarı Raporu ---")
print(f"Accuracy (Doğruluk): {accuracy_score(y_test, y_pred):.4f}\n")
print("Sınıflandırma Raporu:")
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Kaldı (0)', 'İptal Etti (1)'],
            yticklabels=['Kaldı (0)', 'İptal Etti (1)'])
plt.xlabel('Tahmin Edilen')
plt.ylabel('Gerçek Değer')
plt.title('Lojistik Regresyon - Confusion Matrix')
plt.tight_layout()
plt.show()

feature_importance = pd.DataFrame({
    'Öznitelik': X.columns,
    'Katsayı': log_model.coef_[0]
}).sort_values(by='Katsayı', ascending=False)

print("\n--- En Çok Etki Eden İlk 5 Pozitif ve Negatif Faktör ---")
print("İptal Riskini Artıranlar (Pozitif Katsayılar):")
print(feature_importance.head(5))

print("\nMüşteri Bağlılığını Artıranlar (Negatif Katsayılar):")
print(feature_importance.tail(5))